### ISSUE TITLE
Can't use in build

### ISSUE THREAD

**Issue by jamesdbloom** [http-builder-ng/gradle-http-plugin#5]
I have included many plugins in my build without error.

However with you plugin what ever I do the build doesn't recognise the `HttpTask` class.  I may be doing something wrong but I have spent at least 30 minutes trying to get this to work.  Normally with a plugin I don't need to spend more then 1 minute, given I have 18 years experience coding.  I would suggest either your plugin doesn't work or you are doing something non-standard or your instructions are not clear.  Certainly all other plugins I've used are much easier to start using without any issues.

**Comment by cjstehno** [comment]
Thanks for your input; however, without more information regarding the specific errors, there is nothing that can be done. I have had it working in very standard builds and have heard no other complaints or issues.  

Feel free to re-open this issue if you have error messages or other useful information.

**Comment by PFacheris** [comment]
I've encountered a similar issue and am including the output of a run with stacktrace and debug flags enabled in hopes that it's helpful:
[output.txt](https://github.com/http-builder-ng/gradle-http-plugin/files/2142989/output.txt)

Here is the task I attempted to configure:
```
task refreshPlugins(type:HttpTask) {
    config {
        request.uri = 'https://artifactory.dev.adnxs.net/artifactory'
    }
    post {
        request.uri.path = '/api/plugins/reload'
        response.success {
            lifecycle.info 'Plugins reloaded on test instance.'
        }
    }
}
```
and my plugins block:
```
plugins {
  id 'groovy'
  id 'org.hidetake.ssh' version '2.9.0'
  id 'io.github.http-builder-ng.http-plugin' version '0.1.1'
}
```
